### PR TITLE
Add ES6 default export support

### PR DESCRIPTION
**Pull request by yinzara**
Fixes issue #146

Replacement for PR #147

### CODE REVIEW

**Comment by yinzara** [comment]
@jefflau Thoughts?

**Comment by GreenGremlin** [comment]
LGTM!

**Comment by joshuajaco** [comment]
@jefflau anything I can do to get this merged?

**Comment by yinzara** [comment]
@jefflau Everything LGTM on this as well after reviewing again.  I know you have to manage the release of the library so I'll let you click merge.

**Comment by jefflau** [comment]
@yinzara Sorry about the tardiness. I'll merge this in now

**Comment by GreenGremlin** [comment]
Any word on when this might be released?

**Comment by GreenGremlin** [comment]
My apologies, it looks like it was released with v3.0.3, the Github releases page just wasn't updated.

**Pull request merged**
