### PR TITLE
Add default export type

### PR DESCRIPTION
**Pull request by joshuajaco**
Closes https://github.com/jefflau/jest-fetch-mock/issues/146

### CODE REVIEW

**Comment by yinzara** [comment]
Adding a default export to the types file doesn't actually fix the problem.  There is no default export in the types because the javascript implementation doesn't have a default export.

If you're using ES6 or TyepsScript, try using this instead to initialize the library:
```
import "jest-fetch-mock"

fetch.enableMocks()
```

**Comment by yinzara** [comment]
I started to write another comment, however I think your concerns are valid. A library that does not have any form of exported contents that only supplies types and a global scope can be confusing and difficult for others to understand.  There is also no way with the current library to say "Only mock for this one test".

The change you've suggested isn't actually enough to achieve what needs to be done to fix the library.   I'm going to open a new PR with additional changes that should alleviate this confusion.

**Comment by yinzara** [comment]
Moved to PR#148

**Comment by joshuajaco** [comment]
This PR was just meant to type the already existing default export, because we are currently globally mocking fetch with:
```js
require('jest-fetch-mock').enableMocks();
```
and then using it in our tests with:
```ts
const customGlobal: GlobalWithFetchMock = global as GlobalWithFetchMock;
customGlobal.fetch.mockResponse('{}');
```
Which isn't ideal. I applied the changes of this PR locally and it seemed to work in our setup.
However I can see a "Only mock for this one test" feature being useful as well.
Thanks for the help 👍

**Pull request closed without merging**
