### PR TITLE
Add Create-React-App usage details to README

### PR DESCRIPTION
**Pull request by davidjb**
This adds some details around using `jest-fetch-mock` in a Create-React-App environment.

Those who are familiar with in the internals of Create-React-App could adapt the setup instructions, but this makes things easier for the less experienced.  For instance, saves on questions like #42.

### CODE REVIEW

**Comment by jefflau** [comment]
Thanks for this!

**Comment by jefflau** [comment]
I haven't tried this myself, but it looks like it should work just fine - is this your current setup?

**Comment by davidjb** [comment]
Yep, this is fully based off what I'm using in my project. Create react app is fully opinionated in how you have to set up tests so that's right if someone's in the same environment. Thanks for merging!

**Comment by jefflau** [comment]
Cool. I haven't pushed it to npm yet. Will do that today along with another pull request

**Pull request merged**
