### PR TITLE
Updated Jest and Jest Types 

### PR DESCRIPTION
**Pull request by janhartmann**
Adjusted breaking change of generic signature of `MockInstance`:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jest/index.d.ts#L810

### CODE REVIEW

**Comment by simonphilips** [comment]
It's suffices to modify:

`export interface FetchMock extends jest.MockInstance<any> {`

to:

`export interface FetchMock extends jest.MockInstance<any,any[]> {`

and depend on `"@types/jest": "^23.3.14",`

That way you can avoid having to upgrade your requirements to Jest 24 (which can go in some other PR).

**Comment by janhartmann** [comment]
Agreed, hold on.

**Comment by kevcenteno** [comment]
@jefflau Any chance we can get this merged + released?

**Comment by jefflau** [comment]
Ill have a look tomorrow! If its not in tomorrow, nudge me again. It’s chinese new year so things are a little hectic!

________________________________

**Comment by kevcenteno** [comment]
Ah, no worries! 🎆 🐖

**Comment by janhartmann** [comment]
Cheers @jefflau - enjoy it! 🎉

**Comment by ma581** [comment]
Hey @kevcenteno would you please check/merge the fix? :D

**Comment by kevcenteno** [comment]
@ma581 it isn't my repo...

**Comment by janhartmann** [comment]
@jefflau will you be able to release this anytime soon?

**Comment by jefflau** [comment]
Sorry for the wait. I gotta pretty sick just after the new year and haven't had a chance to merge. I'm going to merge now.

**Pull request merged**
